### ISSUE TITLE
Missing `AWS_PROFILE_PIC_BUCKET_NAME` in development image tag

### ISSUE THREAD

**Issue by mglaman** [SoftwareEngineeringDaily/software-engineering-daily-api#301]
Cannot run  `softwaredaily/sedaily-rest-api:develop` as part of frontend development due to missing constant configuration.

```
Error: Config validation error: child "AWS_PROFILE_PIC_BUCKET_NAME" fails because ["AWS_PROFILE_PIC_BUCKET_NAME" is required]
    at Object.<anonymous> (/app/dist/config/config.js:46:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/dist/index.js:15:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
[21:35:26] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by mglaman** [comment]
FWIW cloning the project and running it via docker-composer works, just not the `backend/docker-compose.yml` from the frontend repository.

**Comment by andrewmarklloyd** [comment]
@mglaman good catch. Looks like when I updated some configs I didn't add that env var to the [.env.ci](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/devops/.env.ci), which is used to build the backend docker image, which is then used by the frontend. If you want, you can create a PR to reconcile any diff between that file and the [.env.example](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/blob/develop/.env.example). That would be great!

**Comment by mglaman** [comment]
Will do!

**Comment by andrewmarklloyd** [comment]
@mglaman I was already in the repo and I added this to the `.env.ci`. Note that I also moved from using the `develop` tag to using `latest`, including in the [front end repo](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/develop/backend/docker-compose.yml).

**Comment by andrewmarklloyd** [comment]
Looks like I missed another one but I added and all is working.
